### ISSUE TITLE
camunda-bpm-needle does not inject CaseService

### ISSUE THREAD

**Issue by stefanzilske** [camunda/camunda-bpm-needle#16]
I was trying to use the brand new 2.0-alpha2 of [camunda-bpm-assert](https://github.com/camunda/camunda-bpm-assert) to test my CMMN case. When I setup my test using `ProcessEngineNeedleRule`, I don't get CaseService injected, instead needle injects a mock implementation.

**Comment by jangalinski** [comment]
The CamundaInstancesSupplier is still on the 7.1 level. Soe case is not considered.
You could provide a PR where you:

* set the camunda version to 7.6
* implement the then failing methods on "ProcessEngineServices"

would you like to?

**Comment by stefanzilske** [comment]
Definitely. I will put it on my growing list of things around Camunda I would like to contribute to 😊

For the time being, I managed to unit test my case with just the ProcessEngineRule.

**Comment by jangalinski** [comment]
I switched to 7.6, we should have a new release soon.
