### ISSUE TITLE
release 1.2

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-needle#19]
this extension now supports 7.6.0. Please publish a new release.

Release version: 1.2
Next Dev. Version: 1.3-SNAPSHOT

**Comment by hawky-4s-** [comment]
I released needle today, should be available shortly.

**Comment by jangalinski** [comment]
Thanks a lot!

**Comment by jangalinski** [comment]
Note to self: check https://search.maven.org/#search%7Cga%7C1%7Ccamunda-bpm-needle to verify
