### ISSUE TITLE
Maintainer action required: repository is going to be archived

### ISSUE THREAD

**Issue by lwille** [camunda/camunda-bpm-needle#20]
We're in the process of migrating all community repositories and extensions to a new CI system. This repository didn't show any activity since a long time. Please let us know in this issue if this repository is still actively maintained or should be archived.

/ping @jangalinski

**Comment by jangalinski** [comment]
You can archive this ... with camunda-bpm-mockito, mockito "injectMocks" and the spring testing suite, this became obsolete
